name: Package Application with Pyinstaller

on:
  publish:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: optimize_onboarding

    - uses: actions/upload-artifact@v2
      with:
        name: Onboarding Fill
        path: dist/onboarding_fill/onboarding_fill.exe